export const FONTS = {
  Inter_Black: "Inter_Black",
  Inter_BlackItalic: "Inter_BlackItalic",
  Inter_Bold: "Inter_Bold",
  Inter_BoldItalic: "Inter_BoldItalic",
  Inter_ExtraBold: "Inter_ExtraBold",
  Inter_ExtraBoldItalic: "Inter_ExtraBoldItalic",
  Inter_ExtraLight: "Inter_ExtraLight",
  Inter_ExtraLightItalic: "Inter_ExtraLightItalic",
  Inter_Italic: "Inter_Italic",
  Inter_Light: "Inter_Light",
  Inter_LightItalic: "Inter_LightItalic",
  Inter_Medium: "Inter_Medium",
  Inter_MediumItalic: "Inter_MediumItalic",
  Inter_Regular: "Inter_Regular",
  Inter_SemiBold: "Inter_SemiBold",
  Inter_SemiBoldItalic: "Inter_SemiBoldItalic",
  Inter_Thin: "Inter_Thin",
  Inter_ThinItalic: "Inter_ThinItalic",
};
